### ISSUE TITLE
[Bug] Recording fails with java.io.FileNotFoundException error

### ISSUE THREAD

**Issue by sushidave** [SimpleMobileTools/Simple-Voice-Recorder#87]
Tapping the record button constantly brings up this error:

"Es ist ein Fehler aufgetreten: java.io.FileNotFoundException: /storage/emulated/0/Schlichtes Diktiergerät/2022_01_02_18_25_20.m4a: open failed: EACESS (Permission denied)"

Device: SHIFT6m 
OS: ShiftOS-L - based on Android 8.0.0
App: Version 5.6.2

At launch, permission was granted for the app to both record audio and access photos, media and files.
The error continues to occur after deinstalling and reinstalling the app.

**Comment by tibbi** [comment]
Do other apps work well with files? Havent you disabled some system services or maybe have a rooted device with extra permissions security?

**Comment by sushidave** [comment]
Hi @tibbi, thanks for replying so quickly.

Yes, I tried with two other apps where saving attachments/files to the device works fine.

According to the phone's settings the permissions are as follows:

Settings > "apps & permissions" > "app info" > "Simple Voice Recorder" 
> "permissions": both "microphone" and "storage" are enabled.
> "all permissions": "microphone: record audio": "this app can record audio anytime over the microphone"
> "all permissions": "storage: modify or delete sd card contents
> "all permissions": "storage: read sd card contents"

Settings > "apps & permissions" > "app permissions" > "microphone" > "Simple Voice Recorder": enabled

Settings > "apps & permissions" > app permissions" > "storage" > "Simple Voice Recorder": enabled

The device is not rooted but ShiftOS-L is an OS without Google Services, manufactured by SHIFT (Germany). Therefore it's possible that extra permissions are in place. As far as I know, system services haven't been changed by the user.

If you need further info I'm happy to provide it to you. Just let me know.

**Comment by tibbi** [comment]
retry with 5.8.0

**Comment by sushidave** [comment]
@tibbi Thank you. Installing the APK from GitHub lead to "App could not be installed", so I'll try to install version 5.8.0/5.8.1 from F-Droid when it gets released.

**Comment by sushidave** [comment]
@tibbi Thanks, I tried with 5.8.0 and it brings the same error. Plus this one appears some seconds after:
Fehler: java.lang.IllegalStateException

**Comment by HonestAbe7** [comment]
Yes, same error here. Please fix this.

**Comment by HonestAbe7** [comment]
Attached are 2 screenshots with the error messages:

![1](https://github.com/SimpleMobileTools/Simple-Voice-Recorder/assets/88217236/7f8e892f-98b5-459e-90b9-b28e7c56e830)

![Screenshot_20230912-155028](https://github.com/SimpleMobileTools/Simple-Voice-Recorder/assets/88217236/b1852764-dd0c-4b04-85cb-406acd0c2c95)

**Comment by HonestAbe7** [comment]
This issue has been resolved. Thanks for fixing this. 😁

**Comment by sushidave** [comment]
App upgraded to release 5.12.2. The error messages "java.io.FileNotFoundException: (...) open failed: EACESS (Permission denied) and "java.lang.IllegalStateException" still appear.

**Comment by HonestAbe7** [comment]
Issue is back. Was fixed for me but now broken with latest release.
